# File: .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1. Check out the code
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Python and install Flask dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install backend dependencies
        run: |
          cd server
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test backend
        run: |
          cd server
          # Example: set MongoDB URI if your tests need it
          export MONGO_URI="mongodb://localhost:27017/testdb"
          pytest

      # 3. Set up Node and install React dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install frontend dependencies
        run: |
          cd client
          npm install

      - name: Test frontend
        run: |
          cd client
          npm test -- --watchAll=false
